[package]
name = "tokio-rustls"
version = "0.4.0"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/quininer/tokio-rustls"
homepage = "https://github.com/quininer/tokio-rustls"
documentation = "https://docs.rs/tokio-rustls"
readme = "README.md"
description = "Asynchronous TLS/SSL streams for Tokio using Rustls."
categories = ["asynchronous", "cryptography", "network-programming"]

[badges]
travis-ci = { repository = "quininer/tokio-rustls" }
appveyor = { repository = "quininer/tokio-rustls" }

[dependencies]
futures = "0.1.15"
tokio-io = "0.1.3"
rustls = { git = "https://github.com/ctz/rustls" }
tokio-proto = { version = "0.1.1", optional = true }
webpki = { git = "https://github.com/briansmith/webpki" }

[dev-dependencies]
tokio-core = "0.1.9"
clap = "2.26"
webpki-roots = { git = "https://github.com/briansmith/webpki-roots", branch = "webpki-github" }

[target.'cfg(unix)'.dev-dependencies]
tokio-file-unix = "0.4"
