[package]
name = "server"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]

[dependencies]
tokio-rustls = { path = "../..", default-features = false, features = [ "tokio" ] }

tokio = { version = "0.1.6" }
# futures = "0.2.0-beta"

clap = "2.26"
