[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]

[dependencies]
rustls = "0.12"
webpki = "0.18.0-alpha"
tokio-rustls = { path = "../..", default-features = false, features = [ "tokio" ] }

tokio = "0.1"

clap = "2.26"
webpki-roots = "0.14"

[target.'cfg(unix)'.dependencies]
tokio-file-unix = "0.5"

[target.'cfg(not(unix))'.dependencies]
tokio-fs = "0.1"
