[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]

[dependencies]
rustls = "0.12"
webpki = "0.18.0-alpha"
tokio-rustls = { path = "../..", default-features = false, features = [ "tokio" ] }

tokio = "0.1"
tokio-core = "0.1"
tokio-file-unix = "0.4"

clap = "2.26"
webpki-roots = "0.14"
